### ISSUE TITLE
[Token Transit 1] Nav Bar Button Background Remains Blue After Close

### ISSUE THREAD

**Issue by jjnotjayjay** [mwbassette/Projects#75]
Nav bar functionality overall looks awesome!

One minor note: when opening the nav bar, the button's background turns blue while the nav bar is visible.  However, the button's background stays blue even when the nav bar is closed, until the user interacts with another element on the page.

Generally, the expected behavior would be for the button's background to be blue whenever the nav bar is visible, and for the button to be in its original state whenever the nav bar is hidden.

Recording:
![button-remains-blue](https://github.com/mwbassette/Projects/assets/39274776/02b549a8-c40a-42c5-90bb-5a6b93acd6be)

**Comment by mwbassette** [comment]
Yes, I thought it was strange, but that is how the original TT website behaves. I made it that way to match the site, but personally wouldn't want to do it that way.

**Comment by mwbassette** [comment]
Also strange, I tested on Chrome, Firefox, and Chromium to see if I could repeat the behavior you showed me in the recording, and none of them did.

**Comment by mwbassette** [comment]
I tested inside Chrome's dev tools, but not with the responsive device toolbar toggled. There the issue finally appeared as you mentioned. I'll address the code.

**Comment by mwbassette** [comment]
Resolved.

**Comment by mwbassette** [comment]
Resolved.

**Comment by jjnotjayjay** [comment]
@mwbassette Nevermind - looks like it was included in the other PR!  (Quick note: often in "resolved" message for these "issues", you'll see a link to the commit or PR in which it was resolved.  So for example, your resolved message might have been "Resolved in https://github.com/mwbassette/Projects/pull/77/commits/abcec43fb0e08c4a5dcee5504fbdb6c24c73d1b7"
